# Generated by Django 3.0.6 on 2020-05-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200517_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autentifikacija',
            field=models.BooleanField(default=False),
        ),
    ]
