# Generated by Django 3.0.6 on 2020-05-17 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Naziv')),
                ('content', models.TextField(verbose_name='Opis')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('uplatni_racun', models.CharField(blank=True, max_length=55)),
                ('adresa', models.CharField(blank=True, max_length=55)),
                ('stanje', models.BooleanField(default=True)),
                ('hitnost', models.BooleanField(default=False)),
                ('prikupljeno', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
