# Generated by Django 3.0.6 on 2020-05-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_autentifikacija'),
        ('blog', '0002_zahtjev'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtjev',
            name='hum_org',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
