# Generated by Django 3.0.6 on 2020-05-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200520_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zahtjev',
            name='hum_org',
        ),
    ]
