# Generated by Django 3.0.6 on 2020-05-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_autentifikacija'),
        ('blog', '0006_zahtjev_hum_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahtjev',
            name='hum_org',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
